version: '3'

services:
  airflow:
    build:
      context: ./docker/airflow
      dockerfile: Dockerfile
    container_name: airflow
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - de-network

  livy:
    build:
      context: ./docker/airflow
      dockerfile: Dockerfile
    container_name: spark3
    restart: unless-stopped
    ports:
      - "4040:4040"
      - "7078:7078"
      - "7079:7079"
      - "8088:8088"
      - "10000:10000"
    networks:
      - de-network

networks:
  de-network:
    driver: bridge
